fixed gamemanager not being a singleton. KNOWN ISSUE: player singleton error
this error exists yet the game is still fully functional ?
MissingReferenceException: The object of type 'player' has been destroyed but you are still trying to access it.
Your script should either check if it is null or you should not destroy the object.
GameManager.OnSceneLoaded (UnityEngine.SceneManagement.Scene sc, UnityEngine.SceneManagement.LoadSceneMode mode) (at Assets/Scripts/GameManager.cs:150)